"""Add new columns to table

Revision ID: 84e68736f318
Revises: 
Create Date: 2024-11-25 13:55:15.409809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e68736f318'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ternak', sa.Column('bobot', sa.Float(), nullable=True))
    op.add_column('ternak', sa.Column('waktu_daftar', sa.String(), nullable=True))
    op.add_column('ternak', sa.Column('no_antri', sa.String(), nullable=True))
    op.drop_index('ix_ternak_bobot', table_name='ternak')
    op.create_index(op.f('ix_ternak_bobot'), 'ternak', ['bobot'], unique=False)
    op.create_index(op.f('ix_ternak_karkas'), 'ternak', ['karkas'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ternak_karkas'), table_name='ternak')
    op.drop_index(op.f('ix_ternak_bobot'), table_name='ternak')
    op.create_index('ix_ternak_bobot', 'ternak', ['karkas'], unique=False)
    op.drop_column('ternak', 'no_antri')
    op.drop_column('ternak', 'waktu_daftar')
    op.drop_column('ternak', 'bobot')
    # ### end Alembic commands ###
